name: CI workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10]
    container:
      image: python:${{ matrix.python-version }}-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org
          pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with pytest
        run: |
          pytest -v --tb=short --color=yes --cov=src --cov-report=term-missing

      - name: Generate coverage report
        run: |
          pytest -v --tb=short --color=yes --cov=src --cov-report=xml

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run security analysis with Bandit
        run: |
          bandit -r src/

      - name: SonarQube Scan
        run: |
          sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.sources=src \
          -Dsonar.host.url=http://sonarqube-server:9000 \
          -Dsonar.login=$SONARQUBE_TOKEN

      - name: Security Scan with Trivy
        run: |
          trivy image python:${{ matrix.python-version }}-slim
